### ISSUE TITLE
Filter by server ids

### ISSUE THREAD

**Issue by Metacinnabar** [l1ving/discord-mass-delete#1]
Self explanatory.

**Comment by 5HT2** [comment]
Sure, I can do this today

**Comment by 5HT2** [comment]
Tomorrow*

**Comment by 5HT2** [comment]
I'm unsure how to handle channels that aren't from guilds, I guess I can skip them entirely.

**Comment by Metacinnabar** [comment]
Maybe even `-guilds dms` to delete messages from all dms.

**Comment by 5HT2** [comment]
You can use `-channels` for that

**Comment by 5HT2** [comment]
Well, I can technically do a thing to select *all* dms, but I don't know why somebody would want to do that

**Comment by Metacinnabar** [comment]
Yeah fair enough. I don't see a use-case either. I guess if someone wants this for whatever reason they can create a new issue.
